# permissions for end users to edit dbaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaas-editor-role
rules:
- apiGroups:
  - dbaas.saddleriver.com
  resources:
  - dbaas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.saddleriver.com
  resources:
  - dbaas/status
  verbs:
  - get
