# permissions for end users to view dbaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaas-viewer-role
rules:
- apiGroups:
  - dbaas.saddleriver.com
  resources:
  - dbaas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.saddleriver.com
  resources:
  - dbaas/status
  verbs:
  - get
